### PR TITLE
Add 5-minute shapefile and basemap

### PR DESCRIPTION
**Pull request by mrdufour**
Added 5-inute grid shapefile and basemap

Issue #4

### CODE REVIEW

**Comment by zjslagle** [comment]
Alright, I'm finally trying to review this but I'm a little cautious/confused. I see this fork (add_cb_wb_and_tidy), but I also see that there's a fork called "revert-3-add_cb_wb_and_tidy". @HoldenJe @mrdufour plz help 😢

**Comment by mrdufour** [comment]
Hey Zak, I made that branch a while ago while I was still feeling out the process. Pretty sure it is defunct. From now on, a branch should be created for each issue and merged to the Development. That way, the issue related branches can be closed as we address stuff. Sorry for the confusion. @HoldenJe how do we nix a defunct branch?

**Comment by HoldenJe** [comment]
Click on the branches link (beside the drop down to select a branch). From there you will see all the active branches and should be able to delete from there, unless I haven't granted you enough permissions. Anything that has been merged can also be deleted to avoid confusion. They can always be restored if needed.

**Comment by zjslagle** [comment]
Cool, thanks! Looks like the revert branch was deleted already.

**Comment by mrdufour** [comment]
I just deleted it. @zjslagle can you check out 'base_5mingrid'? It is not presenting as the other 'base_' maps - maybe the original projection is off or something?

**Comment by zjslagle** [comment]
Yeah there was a small issue, the 5 min grid lacked a defined projection. I added a projection in my commit; I think this is good now.

**Pull request merged**
