### PR TITLE
Development

### PR DESCRIPTION
**Pull request by HoldenJe**
Migrates recent changes in Development to Main. Test any existing code to ensure it's working as expected.

### CODE REVIEW

**Comment by zjslagle** [comment]
This looks good to me! Just to be explicit about what I did to check: opened R project, switched to Development branch, pulled, and ran through the scripts. I didn't see anything off (outside of the standard sf warning about "st_point_on_surface may not give correct..." BS.
Anyone else want to review for practice, before a merge?

**Review by zjslagle — COMMENTED** [review]
Ah, meant to leave that comment here, I think. Looks good. Note that there is a difference between simply leaving a comment and adding a review (with comment).

**Review by mrdufour — APPROVED** [review]
Everything looks good to me as well. I think I did the same as Zak, but after pulling the Development branch, I also did - Install and Restarted. All the base_ and shape_ objects look correct to me. How did you fix the 5min grid projection, Zak?

**Comment by zjslagle** [comment]
Pretty simple, just loaded the simple feature, st_set_crs() to define the
crs, then st_write() to save it.

Also, this is a test of replying directly from email, curious to see how it
looks.

**Pull request merged**
