### PR TITLE
Added cb_strata and wb_strata

### PR DESCRIPTION
**Pull request by mrdufour**
Added wb_strata and cb_strata
Changed EB_strata_2 to eb_strata for consistency
Generalized import_EB_strata.R to import_layers.R

### CODE REVIEW

**Comment by HoldenJe** [comment]
I attempted to run a "build and reload" on this branch and it failed. 
```
Warning in data("shape_cbstrata") : data set 'shape_cbstrata' not found
Error in eval(exprs[i], envir) : object 'shape_cbstrata' not found
Error: unable to load R code in package 'eriespatial'
```
I suspect there is a documentation issue. I'll attempt to debug.

**Comment by mrdufour** [comment]
Huh, that's weird. I think it was working on this end. I just reran it here, and seems ok. Maybe I left something out on the push.
________________________________
From: HoldenJe ***@***.***>
Sent: Friday, July 1, 2022 9:51 AM
To: LakeErie-PreyFish-Acoustics/eriespatial ***@***.***>
Cc: Dufour, Mark R ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [LakeErie-PreyFish-Acoustics/eriespatial] Added cb_strata and wb_strata (PR #3)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



I attempted to run a "build and reload" on this branch and it failed.

Warning in data("shape_cbstrata") : data set 'shape_cbstrata' not found
Error in eval(exprs[i], envir) : object 'shape_cbstrata' not found
Error: unable to load R code in package 'eriespatial'


I suspect there is a documentation issue. I'll attempt to debug.

**Comment by HoldenJe** [comment]
I ran `devtools::document()` to create the help files for the layers. Whether it was your additional push or the `document()` that fixed it, build works now on my system.

**Review by HoldenJe — APPROVED** [review]
proceed to merge if you are happy with my additions.

**Comment by mrdufour** [comment]
> So, we need to create that man file for future additions too. Correct?

**Comment by HoldenJe** [comment]
Yes - the `devtools::document()` function should be run for each new addition. It auto-magically creates the documentation files (for `?base_cbstrata`) from the `roxygen` header code in the `cbstrata.r` file. 

One of the steps in the function building process is responsible for adding the function name to the `NAMESPACE` file which controls what variable names are loaded with the package. The error I was getting suggests that the part of the process required to update the `NAMESPACE` wasn't complete since the variable was not available to me. It may have worked on your machine if variable names were still in your local environment.

**Pull request merged**
